// site/src/components/antdv-token-previewer/component-demos/typography/success.tsx
import { defineComponent } from 'vue'
import { Typography } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

const { Title, Text } = Typography

const Demo = defineComponent({
  setup() {
    return () => (
      <div>
        <Title type={'success'} level={4}>
          Success Title
        </Title>
        <Text type={'success'}>success Text</Text>
      </div>
    )
  },
})

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
}

export default componentDemo

// site/src/components/antdv-token-previewer/component-demos/tag/success.tsx
import type { ComponentDemo } from '../../interface';
import { Tag } from '@antdv/ui';

const Demo = () => <Tag color="success">Success</Tag>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess', 'colorSuccessBg', 'colorSuccessBorder'],
  key: 'success',
};

export default componentDemo;
