// site/src/components/antdv-token-previewer/component-demos/tag/success.tsx
import type { ComponentDemo } from '../../interface';
import { Tag } from '@antdv/ui';

const Demo = () => <Tag color="success">Success</Tag>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess', 'colorSuccessBg', 'colorSuccessBorder'],
  key: 'success',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/message/success.tsx
import { defineComponent } from 'vue'
import { Button, message } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

const Demo = defineComponent({
  setup() {
    const success = () => {
      message.success('This is an success message')
    }

    return () => <Button onClick={success}>Success</Button>
  },
})

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
}

export default componentDemo
