// site/src/components/antdv-token-previewer/component-demos/tag/error.tsx
import { Tag } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

const Demo = () => <Tag color="error">Error</Tag>

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorError', 'colorErrorBg', 'colorErrorBorder'],
  key: 'error',
}

export default componentDemo

// site/src/components/antdv-token-previewer/component-demos/alert/error.tsx
import type { ComponentDemo } from '../../interface'
import { Alert, Space } from '@antdv/ui'
import { defineComponent } from 'vue'

const Demo = defineComponent({
  setup() {
    return () => (
      <Space direction="vertical">
        <Alert message="Error" type="error" showIcon />

        <Alert
          message="Error"
          description="This is an error message about copywriting."
          type="error"
          showIcon
        />
      </Space>
    )
  },
})

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorErrorBg', 'colorErrorBorder', 'colorError'],
  key: 'error',
}

export default componentDemo
