// site/src/components/antdv-token-previewer/component-demos/input/danger.tsx
import type { ComponentDemo } from '../../interface';
import { Input } from '@antdv/ui';
import { defineComponent } from 'vue';

function onChange() {}

const Demo = defineComponent({
  setup() {
    return () => <Input status="error" defaultValue="hello" onChange={onChange} />;
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorError', 'colorErrorOutline', 'colorErrorBorder', 'colorErrorHover'],
  key: 'danger',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/datePicker/danger.tsx
import type { ComponentDemo } from '../../interface'
import { DatePicker } from '@antdv/ui'

const Demo = () => <DatePicker status="error" />

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorError', 'colorErrorBorder', 'colorErrorHover', 'colorErrorOutline'],
  key: 'danger',
}

export default componentDemo
