// site/src/components/antdv-token-previewer/component-demos/checkbox/disabled.tsx
import type { ComponentDemo } from '../../interface'
import { Checkbox } from '@antdv/ui'

const Demo = () => <Checkbox disabled>Checkbox</Checkbox>

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorTextDisabled', 'colorBgContainerDisabled'],
  key: 'disabled',
}

export default componentDemo

// site/src/components/antdv-token-previewer/component-demos/datePicker/disabled.tsx
import type { ComponentDemo } from '../../interface'
import { DatePicker, Space } from '@antdv/ui'
import { defineComponent } from 'vue'

const Demo = defineComponent({
  setup() {
    return () => (
      <Space direction="vertical">
        <DatePicker disabled />
        <DatePicker disabled picker="week" />
        <DatePicker disabled picker="month" />
        <DatePicker disabled picker="quarter" />
        <DatePicker disabled picker="year" />
      </Space>
    )
  },
})

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorBgContainerDisabled', 'colorTextDisabled'],
  key: 'disabled',
}

export default componentDemo
