// site/src/components/antdv-token-previewer/component-demos/inputNumber/warning.tsx
import { defineComponent } from 'vue'
import { InputNumber } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

function onChange() {}

const Demo = defineComponent({
  setup() {
    return () => (
      <InputNumber status={'warning'} min={1} max={10} defaultValue={3} onChange={onChange} />
    )
  },
})

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorWarning', 'colorWarningBorder', 'colorWarningOutline', 'colorWarningHover'],
  key: 'warning',
}

export default componentDemo

// site/src/components/antdv-token-previewer/component-demos/datePicker/warning.tsx
import { DatePicker } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

const Demo = () => <DatePicker status="warning" />

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorWarning', 'colorWarningBorder', 'colorWarningHover', 'colorWarningOutline'],
  key: 'warning',
}

export default componentDemo
