// site/src/components/antdv-token-previewer/component-demos/result/warning.tsx
import type { ComponentDemo } from '../../interface';
import { Result } from '@antdv/ui';

import { defineComponent } from 'vue';

const Demo = defineComponent({
  setup() {
    return () => <Result status="warning" title="Demo示意" subTitle="status 为warning" />;
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorWarning'],
  key: 'warning',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/datePicker/warning.tsx
import { DatePicker } from '@antdv/ui'
import type { ComponentDemo } from '../../interface'

const Demo = () => <DatePicker status="warning" />

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorWarning', 'colorWarningBorder', 'colorWarningHover', 'colorWarningOutline'],
  key: 'warning',
}

export default componentDemo
